version: "3.9"

services:
  db:
    image: postgres:15
    container_name: webhooks_db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: webhooks
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d webhooks" ]
      interval: 5s
      timeout: 5s
      retries: 10
  
  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8080
      APP_ENV: local
      DB_URL: postgres://postgres:postgres@db:5432/webhooks?sslmode=disable
      STRIPE_SIGNING_SECRET: placeholder #Reference variable in .env
      GRACEFUL_TIMEOUT_SECONDS: 10
    ports:
      - "8080:8080"

volumes:
  db_data: {}